### Send Admin Invitation
POST http://localhost:8080/admins/send-invite
Content-Type: application/json

{
    "email": "juanvictorqwerty@gmail.com"
}
###

### Accept Admin Invitation
POST http://localhost:8080/admins/accept-invitation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqdWFudmljdG9ycXdlcnR5QGdtYWlsLmNvbSIsImlhdCI6MTc3ODQyNzE4NCwiZXhwIjoxNzc4NDI3MTg4fQ.dzY-WtGrmI44wrRWgHPZDxtxRkFLqCfxPAp5Gn3A1xo


{
    "password": "password123"
}

###