### Send Pharmacist Invitation
POST http://localhost:8080/admins/invite-pharmacist
Content-Type: application/json

{
    "email": "pharmacist@example.com"
}

###

### Accept Pharmacist Invitation
POST http://localhost:8080/api/admin/invite-pharmacist/accept
Content-Type: application/json

{
    "code": "123456",
    "email": "pharmacist@example.com",
    "password": "password123"
}

###