### Create Super Admin
POST http://localhost:8080/api/superadmin/creation/create_superAdmin
Content-Type: application/json

{
    "email": "juanvictor.mike@ictuniversity.edu.cm",
    "secretCode": "0000099999",
    "password": "12345678"
}

###

### Check Email
GET http://localhost:8080/api/superadmin/creation/check_email?email=test@example.com

###